name: Create Jira Ticket
description: Create a ticket on Scoober board
inputs:
  jira_project_url:
    required: true
    description: Jira Project URL
  jira_user:
    required: true
    description: Jira User Name
  jira_access_token:
    required: true
    description: Jira Access Token
  jira_project_id:
    required: true
    description: Jira Project Id
  ticket_parent_id:
    required: true
    description: Jira Ticket Parent Id
  ticket_title:
    required: true
    description: Ticket Title
  ticket_description:
    required: true
    description: Ticket Description
outputs:
  jira-ticket-id:
    description: "Jira Ticket id number"
    value: ${{ steps.create-jira-ticket.outputs.jira-ticket-id }}

runs:
  using: composite
  steps:
    - name: Create Jira Tikcet
      id: create-jira-ticket
      # issueType 3 means we are creating a task
      shell: bash
      run: |
        response=$(curl --location "https://reqres.in/api/users/2" \
        --header 'Content-Type: application/json')
        echo "api-response=$(echo $response)"
        echo "jira-ticket-id=$(echo ${api-response} | jq -r '.data.first_name')" >> $GITHUB_OUTPUT
