name: Create Sync Release Branch
description: Create RP to Sync Develop with Branch
inputs:
  release-branch-name:
    required: true
    description: Name of release branch
  github-pat:
    required: true
    description: GitHub Personal Access Token

runs:
  using: composite
  steps:
    - name: Sync branch name
      shell: bash
      run: |
        echo "SYNC_RELEASE_BRANCH=sync/${{ inputs.release-branch-name }}-$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Setup Git configuration
      shell: bash
      run: |
        git config --global --add safe.directory /__w/scoober-courier-android/scoober-courier-android
        git config user.name "Scoober GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"

    - name: Create new sync branch
      shell: bash
      run: |
        git checkout -b ${{ env.SYNC_RELEASE_BRANCH }} ${{ inputs.release-branch-name }}

    - name: Check for changes
      id: check_changes
      shell: bash
      run: |
        if [[ $(git status --porcelain) ]]; then
          echo "Changes detected."
          git add .
          git commit -m "Committing changes before creating PR"
        else
          echo "No changes detected."
        fi

    - name: Create new branch
      shell: bash
      run: |
        git push origin ${{ env.SYNC_RELEASE_BRANCH }} 

    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-pat }}
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: 'Sync release branch ${{ inputs.release-branch-name }}',
            owner,
            repo,
            head: '${{ env.SYNC_RELEASE_BRANCH }}',
            base: 'develop',
            body: [
              'This is an auto-generated PR for syncing the release branch with develop. It also includes increase of app version for next release or hotfix.',
              'Sync release branch ${{ inputs.release-branch-name }} to develop'
            ].join('\n')
          });

