name: Create Sync Release Branch
description: Create Sync Release Branch
inputs:
  release-branch-name:
    required: true
    description: Name of release branch
  github-pat:
    required: true
    description: GitHub Personal Access Token

runs:
  using: composite
  steps:
    - name: Create new branch name
      shell: bash
      run: |
        echo "SYNC_RELEASE_BRANCH=sync_release/5.0.0-$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Create new branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout -b ${{ env.SYNC_RELEASE_BRANCH }} ${{ inputs.release-branch-name }}

    - name: Check for changes
      id: check_changes
      run: |
        if [[ $(git status --porcelain) ]]; then
          echo "Changes detected."
          git add .
          git commit -m "Committing changes before creating new branch"
        else
          echo "No changes detected."
        fi

    - name: Create new branch
      run: |
        git push origin ${{ env.SYNC_RELEASE_BRANCH }} 

    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-pat }}
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: '[Example] Simple demo',
            owner,
            repo,
            head: '${{ env.SYNC_RELEASE_BRANCH }}',
            base: 'develop',
            body: [
              'This PR is auto-generated by',
              '[actions/github-script](https://github.com/actions/github-script).'
            ].join('\n')
          });

