name: Bi-weekly Branch Creation

on:
  workflow_dispatch:

    inputs:
      release-branch-name:
        description: 'Release Branch Name'
        required: true
        type: string
      start-date:
        description: 'Start Date of Workflow'
        required: true
        type: string

jobs:
  is_bi_weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make the script files executable
        run: chmod +x scripts/biweekly.sh

      - name: Calculate weekdiff
        id: calculate
        shell: bash
        run: |
          weekindex=$(./scripts/biweekly.sh "${{ inputs.start-date }}")
          echo "weekindex=$weekindex"
          if [ $weekindex -eq 0 ]; then
            echo "🟢 It's the first week of the bi-weekly cycle. The action is going to run."
            echo "run_next_workflow=true" >> $GITHUB_OUTPUT
          else
            echo "🔴 It's the second week of the bi-weekly cycle. The action is going to be skipped."
            echo "run_next_workflow=false" >> $GITHUB_OUTPUT
          fi

  create-release-branch:
    if: ${{ needs.is_bi_weekly.outputs.run_next_workflow == 'true' }}
    needs: is_bi_weekly
    uses: QumberAbbas/increaseTags/.github/workflows/release-branch-creation.yml@develop
    with:
      release-branch-name: ${{ inputs.release-branch-name }}


