# This is a basic workflow that is manually triggered

name: Bi-weekly Branch Creation

on:
  workflow_dispatch:

    inputs:
      start-date:
        description: 'Creation of release branch'
        required: true
        type: string

jobs:
  is_bi_weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate weekdiff
        id: calculate
        shell: bash
        working-directory: "${{ github.workspace }}/scripts"
        run: |
          echo "Files in current directory:"
          ls -l
