name: Scheduled Job

on:
  schedule:
    - cron: '40 11 * * 2'

jobs:
  publish_tag:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Say Hello
        id: get_version
        run: echo "Hello I am Scheduled Job"