name: Publish Tag for Development Branch

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    
jobs:
  publish_tag:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Get the version
      id: get_version
      run: echo "VERSION_NUMBER_CI=$(echo $GITHUB_REF | sed -n 's/refs\/tags\///p')" >> $GITHUB_ENV

    - name: Create Jira Ticket
      id: create_jira_ticket
      uses: ./.github/actions/create-jira-ticket-for-release-sync
      with:
        jira_project_url: ${{ secrets.JIRA_PROJECT_URL }}
        jira_project_id: ${{ secrets.JIRA_PROJECT_ID }}
        jira_user: ${{ secrets.JIRA_USER }}
        jira_access_token: ${{ secrets.JIRA_API_KEY }}
        ticket_parent_id: ${{ secrets.JIRA_PARENT_TICKET }}
        ticket_title: "Test Ticket for syncing release branch ${{ env.VERSION_NUMBER_CI }} with develop"
        ticket_description: "Test ticket description"

    - name: Extract Key from Jira Ticket Creation Response
      id: extract_key
      run: |
        echo "Id is ${{ steps.create_jira_ticket.outputs.jira-ticket-id }}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Increase app version
        title: "This is ticket title ${{ steps.create_jira_ticket.outputs.jira-ticket-id }}"
        body: This is an auto-generated PR for increasing app semantic version
        branch: "sync_release/${{ env.VERSION_NUMBER_CI }}_to_develop"
        base: 'refs/heads/develop'
        delete-branch: true

    - name: Check Tag Name and Do Something
      if: endsWith(github.ref, '.0')
      run: |
        version="${{ github.ref }}"
          if [[ $version =~ \.0$ ]]; then
            echo "Performing an action for version $version."
          else
            echo "Performing another action for version $version."
          fi
