name: Publish Tag for Development Branch

on:
  push:
    branches:
      - develop
      - 'release**'
    
jobs:
  publish_tag:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0


    - name: Get the ticket number
      id: get_version
      run: echo "TICKET_NUMBERS=SCAT-5249" >> $GITHUB_ENV
      shell: bash

    - name: Get the ticket number
      id: get_versions
      run: echo "VERSION_NUMBER_CI=3.5.0-alpha.1" >> $GITHUB_ENV
      shell: bash

      

    - name: Add Jira Comment for Published Tag
      if: ${{ env.TICKET_NUMBERS != '' && env.TICKET_NUMBERS != null }}
      run: |
        curl --location "${{ secrets.URL }}/${{ env.TICKET_NUMBERS }}/comment" \
        --user "${{ secrets.USER }}:${{ secrets.PASSWORD }}" \
        --header 'Content-Type: application/json' \
        --data '{"body":{"version":1,"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"'"${{ env.VERSION_NUMBER_CI }}"'","marks":[{"type":"link","attrs":{"href":"'"${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/tag/${{ env.VERSION_NUMBER_CI }}"'"}}]}]}]}}'
          
  

