name: Manual workflow

on:
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Read App Version
      id: read_version
      run: echo "VERSION=$(sed '2q;d' version.properties)" >> $GITHUB_ENV

    - name: Increase tag version
      id: increase_version
      run: |
          VERSION=$(echo ${{ env.VERSION }} | awk -F'[-.]' '{print $1"."$2"."$3"-alpha."$5 + 1}')
          echo "NEW_TAG=$VERSION" >> $GITHUB_ENV
          
    - name: Print new tag
      id: create_tag
      run: echo "${{ steps.latest_tag.outputs.NEW_TAG}}"
      
