name: Publish Tag for Development Branch

on:
  push:
    branches:
      - develop
    
jobs:
  publish_tag:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
        
    - name: Fetch Upcoming Release Version
      id: fetch_upcoming_release_version
      run: |
          VERSION=$(grep '^version=' version.properties | cut -d'=' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Check If Release Branch Is Already Created
      #If release branch is created and we don't have version updated in version.properties then we will increment tag as this commit is targetting dev branch not release.
      id: check_release_branch_exists
      run: |
        if git show-ref --verify --quiet "refs/remotes/origin/release/${{ env.VERSION }}"; then
          echo "release_branch_exists=true" >> $GITHUB_OUTPUT
        else
          echo "release_branch_exists=false" >> $GITHUB_OUTPUT
        fi        
        
    - name: Increase App Minor Version If release branch is already created and Create Tag
      id: increase_app_version
      if: success() && steps.check_release_branch_exists.outputs.release_branch_exists == 'true'
      run: |
        IFS='.' read -r major minor patch <<< "$VERSION"
        ((minor++))
        NEW_VERSION="${major}.${minor}.${patch}"
        NEW_TAG="${NEW_VERSION}-alpha.1"
        echo "TAG=$NEW_TAG" >> $GITHUB_ENV
          
    - name: Increase Tag for Stage If release branch isn't created
      if: steps.increase_app_version.outcome == 'skipped'
      run: |
          TAG=$(git tag --list "$VERSION-alpha.*" --sort=-version:refname | head -n 1)
          NEW_TAG=$(echo "$TAG" | awk -F'[-.]' '{print $1"."$2"."$3"-alpha."$5 + 1}')
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Push Git Tag
      run: |
          git config user.name "Scoober GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{env.NEW_TAG}}
          git push origin ${{env.NEW_TAG}}
      
    - name: Print New tag
      id: create_tag
      run: echo "${{ env.NEW_TAG}}"
      
