name: 'Notify Failures'

on:
  workflow_run:
    workflows: [ Build and Publish to Staging,  Publish Tag for Development Branch ]
    types: [ completed ]

env:
  JOB_URL: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}

jobs:
  on-failure:
    name: Send Slack Notification
    if: github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.conclusion == 'timed_out' || github.event.workflow_run.conclusion == 'cancelled'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0