name: Publish tag for development branch

on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        description: Release version to publish to Google Play Store Internal Channel
      fetch_translations:
        required: false
        type: choice
        default: 'no'
        description: Should fetch latest translations
        options:
          - yes
          - no

jobs:
  publish_app_to_prod:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release/${{ github.event.inputs.release_version }}

      - name: Get the version
        if: ${{ github.event.inputs.fetch_translations == 'yes' }}
        run: |
          echo "🟢 Translations are going to be fetched"

      - name: Create and push a tag
        run: |
          git tag ${{ github.event.inputs.release_version }}
          git push origin ${{ github.event.inputs.release_version }}
      


