name: Build and Publish to Staging
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-stage+.[0-9]+"

jobs:
  build-and-deploy-to-stage:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Pull Request data
        id: get_pr_data
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const getPullRequestData = require('get_pr_data');
            return getPullRequestData(github, context);

      - name: Pull Request data
        run: |
          echo "PR Number: ${{ steps.get_pr_data.outputs.result.number }}"
          echo "PR Title: ${{ steps.get_pr_data.outputs.result.title }}"

