name: Build and Publish to Staging
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-alpha+.[0-9]+"

jobs:
  build-and-deploy-to-stage:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Commit Data
        run: |
          echo "Commit SHA: ${{ context.sha }}"
          echo "Owner: ${{ context.repo.owner }}"
          echo "Repo: ${{ context.repo.owner }}"
          
      - uses: actions/github-script@v7
        id: get_pr_data
        with:
          script: |
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0];
      - name: Pull Request data
        run: |
          echo "PR Number: ${{ steps.get_pr_data.outputs.result.number }}"
          echo "PR Title: ${{ steps.get_pr_data.outputs.result.title }}"

