name: Workflow Build and Publish to Production
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-deploy-to-stage:
    
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: Get the version
        id: get_version
        run: echo "RELEASE_BRANCH=release/$(echo $GITHUB_REF | sed -n 's/refs\/tags\///p'  | sed 's/\.[0-9]*$/\.0/')" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "${{ env.RELEASE_BRANCH }}"

      - name: Compare branches
        run: |
          git fetch origin develop
          git log origin/${{ env.RELEASE_BRANCH }} ^origin/develop --oneline

      - name: Get github token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.ANDROID_GITHUB_APP_ID }}
          application_private_key: ${{ secrets.ANDROID_GITHUB_APP_PRIVATE_KEY }}

      - name: Create file and add text
        run: |
          echo "Hello, world!" > example.txt
          echo "This is a test file." >> example.txt

      - name: Create new branch name
        uses: actions/create-sync-release-branch
        with:
          release-branch-name: ${{ env.RELEASE_BRANCH }}
          github-pat: ${{ steps.get_workflow_token.outputs.token }}