name: Build and Publish to Staging
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-deploy-to-stage:
    
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      

      - name: Get github token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.ANDROID_GITHUB_APP_ID }}
          application_private_key: ${{ secrets.ANDROID_GITHUB_APP_PRIVATE_KEY }}

      - name: Get the version
        id: get_version
        run: echo "RELEASE_BRANCH=release/$(echo $GITHUB_REF | sed -n 's/refs\/tags\///p'  | sed 's/\.[0-9]*$/\.0/')" >> $GITHUB_ENV   

      - name: Rebase sync_release/3.7.0 with release/3.7.0
        run: |
          git checkout -b sync_release/3.7.0
          git rebase ${{ env.RELEASE_BRANCH }}
          git push --force origin sync_release/3.7.0

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          commit-message: "Sync release branch to develop"
          title: "Sync release branch to develop"
          body: This is an auto-generated PR for syncing the release branch with develop. It also includes increase of app version for next release or hotfix.
          branch: "sync_release/3.7.0"
          base: "develop"
          delete-branch: true
